shopping_list=[]#列表可变
example_tuple=('A','B')#元组不可变
shopping_list.append('keyboard')
print(shopping_list)
print(example_tuple)
shopping_list.append('mouse')
shopping_list.append(5090)
shopping_list.append('screen')
shopping_list.append('microphone')
print(shopping_list)
shopping_list.remove('microphone')
print(shopping_list)
print('购物清单长度为'+str(len(shopping_list)))

list2=(2,44,77,17,27,8,4)
print(list2)
print(sorted(list2))
print(max(list2))
print(min(list2))